config/urls.py
from django.contrib import admin
from django.urls import path, include

# import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('ipam/', include('ipledger.urls')),
]

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

ipledger/urls.py
from django.urls import path

from .views import *

app_name = 'ipledger'

urlpatterns = [
    path('', IndexView.as_view(), name='index' ),
    path('iplist/', IpBaseListView.as_view(), name='iplist'),
    path('seglist/', SegBaseListView.as_view(), name='seglist'),
    path('hostlist/', HostListView.as_view(), name='hostlist'),
    path('segcreate/', SegmentGenericView.as_view(), name='segcreate'),
    path('segdetail/<int:pk>', SegDetailView.as_view(), name='segdetail'),
    path('segdelete/<int:pk>', SegDeleteView.as_view(), name='segdelete'),
    path('hostdetail/<int:pk>', HostDetailView.as_view(), name='hostdetail'),
    path('hostcreate/', HostGenericOnlyView.as_view(), name='hostcreate'),
    path('hostupdate/<int:pk>', HostAssignView.as_view(), name='hostassign'),
    path('hostdelete/<int:pk>', HostDeleteView.as_view(), name='hostdelete')
]

ipledger/models.py
from django.db import models

from django.core.exceptions import ValidationError
# Create your models here.

UNIT_KINDS = (
    ('server', 'サーバ'),
    ('network', 'ルータ/スイッチ'),
    ('client/static', 'クライアント/静的割当'),
    ('client/DHCP', 'クライアント/DHCP'),
    ('gateway', 'ゲートウェイ'),
    ('other', 'その他機器'),
)

ADDRESS_TYPE = (
    ('service', 'サービス'),
    ('manage', '管理'),
    ('storage', 'ストレージ'),
    ('HA', '高可用性')
)


class SegmentModels(models.Model):

    class Meta:
        db_table = 'segment'

    segment_id = models.AutoField(primary_key=True)
    segment_name = models.CharField(verbose_name='ネットワーク名', null=True, blank=True, max_length=64)
    nw_address = models.CharField(verbose_name='ネットワークアドレス', max_length=15, null=False, unique=True)
    prefix = models.IntegerField(verbose_name='プレフィックス長', null=False)
    seg_description = models.CharField(verbose_name='ネットワークの説明', max_length=128, null=True, blank=True)
    register_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.segment_id}_{self.nw_address}'


class HostModels(models.Model):
    class Meta:
        db_table = 'hosts'

    host_id = models.AutoField(primary_key=True)
    hostname = models.CharField(unique=True, max_length=15)
    host_description = models.CharField(null=True, blank=True, max_length=128)
    kinds = models.CharField(choices=UNIT_KINDS, max_length=30)
    change_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.host_id}_{self.hostname}'


class V4addressModels(models.Model):

    class Meta:
        db_table = 'v4address'

    v4address_id = models.AutoField(primary_key=True)
    host_address = models.CharField(unique=True, max_length=15)
    address_type = models.CharField(choices=ADDRESS_TYPE, max_length=32)
    fore_segment = models.ForeignKey(SegmentModels, null=True, blank=True, on_delete=models.CASCADE)
    fore_host = models.ForeignKey(HostModels, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.v4address_id}_{self.host_address}'

templates/base.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!doctype html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block page_title %}{% endblock page_title %}</title>
</head>
<body>
    {% include 'messages.html' %}
    <div class="container">
    {% block content %}{% endblock content %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>#}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
</body>

templates/create-host.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block page_title %}ホスト作成画面{% endblock page_title %}

{% block content %}
    <div>
      <form method="POST" enctype="multipart/form-data">
         {% csrf_token %}
         {% bootstrap_form form %}
          <div class="d-grid gap-2">
              <button class="btn btn-primary" type="submit">登録</button>
          </div>
      </form>
    </div>
{% endblock content %}

templates/create-seg.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block page_title %}セグメント作成画面{% endblock page_title %}

{% block content %}

    <div class="card">
        <div class="card-header">
            セグメント払い出し
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                <table class="table ">
                {% bootstrap_form form %}
                </table>
                <button class="btn btn-primary" type="submit">登録</button>
            </form>
        </div>

    </div>


{% endblock content %}

templates/host-delete.html
{% extends 'base.html' %}

{% block page_title %}{{ object.hostname }}削除確認画面{% endblock page_title %}

{% block content %}
    <div>
        <p>以下のホストを削除しますか？</p>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>ホストネーム</th>
                    <th>説明</th>
                    <th>ホストタイプ</th>
                    <th>登録日</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ object.hostname }}</td>
                    <td>{{ object.host_id }}</td>
                    <td>{{ object.host_description }}</td>
                    <td>{{ object.kinds }}</td>
                    <td>{{ object.change_date }}</td>
                </tr>
            </tbody>
        </table>
        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">削除</button>
            <a class="btn btn-primary" href="{% url 'ipledger:hostlist' %}">キャンセル</a>
        </form>
    </div>
{% endblock content %}

templates/host-detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">{{ object.hostname }}</h5>
        </div>
        <div class="card-body">
            <p class="card-text">機器種別:{{ object.kinds }}</p>
            <p class="card-text">説明:{{ object.host_description }}</p>
            割当IPアドレス
            <ol>
            {% for item in object.v4addressmodels_set.all %}
                <li>{{ item.address_type }} {{ item.host_address }} </li>
            {% endfor %}
            </ol>
        </div>
        <div class="card-footer text-muted">
            登録日:{{ object.change_date }}
        </div>
    </div>
{% endblock content %}

templates/host-list.html
{% extends 'base.html' %}

{% block page_title %}ホスト一覧{% endblock page_title %}

{% block content %}
    <div>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>ホストネーム</th>
                <th>ホスト種別</th>
                <th>説明</th>
                <th>登録日</th>
                <th>割当IP</th>
                <th>編集</th>
            </tr>
            </thead>
            <tbody>
            {% for item in object_list %}
                <tr>
                    <td>{{ item.hostname }}</td>
                    <td>{{ item.kinds }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.change_date }}</td>
                    <td>
                        <ol>
                        {% for ip in item.v4addressmodels_set.all %}
                            <li>{{ ip.address_type }}:{{ ip.host_address }}</li>
                        {% endfor %}
                        </ol>
                    </td>
                    <td><a class="btn btn-primary" href="{% url 'ipledger:hostdelete' item.host_id %}">削除</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

templates/hostassign.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block page_title %}{{ object.host_address }}ホスト割当画面{% endblock page_title %}

{% block content %}
    <div class="card">
        <div class="card-header">
            {{ object.host_address }}にホスト割当
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                <table class="table">
            {% bootstrap_form form %}
                </table>
                <button class="btn btn-primary" type="submit">割当</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block page_title %}Simple IPAM{% endblock page_title %}

{% block content %}
    <h1>Simple IP Address Manager</h1>

    <h3>一覧ページ</h3>
    <ul>
        <li><a href="{% url 'ipledger:seglist' %}">セグメント一覧ページ</a></li>
        <li><a href="{% url 'ipledger:iplist' %}">IPアドレス一覧ページ</a></li>
        <li><a href="{% url 'ipledger:hostlist' %}">ホストアドレス一覧ページ</a></li>
    </ul>
    <h3>作成ページ</h3>
    <ul>
        <li><a href="{% url 'ipledger:segcreate' %}">セグメント作成ページ</a></li>
        <li><a href="{% url 'ipledger:hostcreate' %}">ホスト作成ページ</a></li>
    </ul>
{% endblock content %}

templates/iplist.html
{% extends 'base.html' %}

{% block page_title %}{% endblock page_title %}

{% block header %}{% endblock header %}

{% block content %}
    <h1>IP 一覧表</h1>
    <table class="table table-sm table-striped table-hover">
        <tr><th>IPアドレス</th><th>ネットワーク</th><th>割り当てホスト</th></tr>
    {% for item in object_list %}
        <tr><td>{{ item.host_address }}</td><td>{{ item.fore_segment.nw_address }}/{{ item.fore_segment.prefix }}</td><td>{{ item.fore_host.hostname }}</td></tr>
    {% endfor %}
    </table>

{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/seg-delete.html
{% extends 'base.html' %}

{% block page_title %}{{ object.segment_name }}削除確認{% endblock page_title %}

{% block content %}
    <div>
        <p>以下のネットワークを削除しますか？<br>※IPアドレスも自動的に削除、開放されます</p>
        <table class="table table-hover">
            <thead>
            <tr><th>ID</th><th>セグメント名</th><th>ネットワークアドレス</th><th>登録日</th><th>説明</th></tr>
            </thead>
            <tbody>
                <tr><td>{{ object.segment_id }}</td><td>{{ object.segment_name }}</td><td>{{ object.nw_address }}/{{ object.prefix }}</td><td>{{ object.register_date }}</td><td>{{ object.seg_description }}</td></tr>
            </tbody>
        </table>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">削除</button>
            <a class="btn btn-primary" href="{% url 'ipledger:seglist' %}">キャンセル</a>
        </form>
    </div>
{% endblock content %}

templates/seg-detail.html
{% extends 'base.html' %}

{% block page_title %}{{ page_title }}のホスト一覧{% endblock page_title %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>ホストアドレス</th>
            <th>アドレス種別</th>
            <th>割当ホスト</th>
            <th>選択</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td>{{ item.host_address }}</td>
                <td>{{ item.address_type }}</td>
                {% if item.fore_host %}
                    <td><a href="{% url 'ipledger:hostdetail' item.fore_host.host_id %}">{{ item.fore_host.hostname }}</a></td>
                {% else %}
                    <td><a class="btn btn-primary btn-sm" href="{% url 'ipledger:hostassign' item.v4address_id %}">ホスト割当</a></td>
                {% endif %}
                <td><input class="form-check-input" type="checkbox" name="unassign" value="{{ item.v4address_id }}"></td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
        <button class="btn btn-primary" type="submit">選択したアドレスのホストを一括解除する</button>
    </form>
{% endblock content %}

templates/seglist.html
{% extends 'base.html' %}

{% block page_title %}ネットワーク一覧{% endblock page_title %}

{% block header %}{% endblock header %}

{% block content %}
    <table class="table table-striped table-hover">
        <thead>
            <tr><th>ID</th><th>セグメント名</th><th>ネットワークアドレス</th><th>登録日</th><th>説明</th><th>詳細</th><th>削除操作</th></tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr><td>{{ item.segment_id }}</td><td>{{ item.segment_name }}</td><td>{{ item.nw_address }}/{{ item.prefix }}</td><td>{{ item.register_date }}</td><td>{{ item.seg_description }}</td><td><a class="btn btn-primary" href="{% url 'ipledger:segdetail' item.segment_id %}">IPアドレス一覧へ</a></td><td><a class="btn btn-primary" href="{% url 'ipledger:segdelete' item.segment_id%}">削除確認画面へ</a></td></tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}